"""Initial commit

Revision ID: 461d261c81c8
Revises: ec50fc7cdbe7
Create Date: 2024-10-07 15:40:33.624754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461d261c81c8'
down_revision: Union[str, None] = 'ec50fc7cdbe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cancelled_orders', 'cancelled_time',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('menus', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'extra_requests',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'ordered_at',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('preparing_orders', 'prepared_at',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ready_orders', 'ready_at',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('restaurants', 'merchant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('restaurants', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('settled_orders', 'settled_at',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settled_orders', 'settled_at',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('restaurants', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restaurants', 'merchant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ready_orders', 'ready_at',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('preparing_orders', 'prepared_at',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('orders', 'ordered_at',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('order_items', 'extra_requests',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('menus', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cancelled_orders', 'cancelled_time',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
