name: Build, Test and Deploy

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Setup virtual environment
        run: python3 -m venv venv && source venv/bin/activate

      - name: Install dependencies
        run: pip install -e .

      - name: Run tests
        run: pytest api/tests/*.py

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest . --platform linux/amd64

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest
