name: Build, Test and Deploy

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Setup virtual environment
        run: python3 -m venv venv && source venv/bin/activate

      - name: Install dependencies
        run: pip install -e .

      - name: Run tests
        run: pytest api/tests/*.py

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push the image
        run: REPO_NAME=`echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'` && docker build . -t ghcr.io/${REPO_NAME}:latest && docker push ghcr.io/${REPO_NAME}:latest
